on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Publish to PyPi
jobs:
  copyRoutes:
    name: Copy routes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Get NPM Dependencies
      run: |
        npm install
    - name: Copy routes
      run: |
        cp -r ./node_modules/@octokit/routes/ octokit_routes/
        rm octokit_routes/routes/package.json
    - name: Copy webhooks
      run: |
        mkdir -p octokit_routes/webhooks
        cp ./node_modules/@octokit/webhooks-definitions/index.json octokit_routes/webhooks/index.json
    - name: Check
      run: |
        python setup.py check
    - name: Test
      run: |
        python -m unittest
    - name: Package
      run: |
        pip install wheel
        python setup.py bdist_wheel sdist
    - name: PyPi Check Upload
      env:
        PIP_INDEX_URL: "https://pypi.org/simple/"
      run: |
        PACKAGE_NAME=$(python setup.py --name)
        PACKAGE_VERSION=$(python setup.py --version)
        curl -s "$PIP_INDEX_URL$PACKAGE_NAME/" | grep "$PACKAGE_NAME-$PACKAGE_VERSION"
    - name: Finish well
      if: github.event_name != 'push' && failure()
      run: |
        echo "Will upload a new version"
    - name: PyPi Twine Upload
      if: github.event_name == 'push' && failure()
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      run: |
        pip install twine
        twine upload dist/*
