on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Publish to PyPi
jobs:
  copyRoutes:
    name: Copy routes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        version: 3.8
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - name: Get NPM Dependencies
      run: |
        npm install
    - name: Copy routes
      run: |
        cp -r ./node_modules/@octokit/routes/ octokit_routes/
        rm octokit_routes/routes/package.json
    - name: Copy webhooks
      run: |
        mkdir -p octokit_routes/webhooks
        cp ./node_modules/@octokit/webhooks-definitions/index.json octokit_routes/webhooks/index.json
    - name: Check
      run: |
        python setup.py check
    - name: Test
      run: |
        python -m unittest
    - name: Package
      run: |
        pip install wheel
        python setup.py bdist_wheel sdist
    - name: PyPi Twine Upload
      if: github.event_name == 'push'
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      run: |
        pip install twine
        twine upload dist/*
